sudo: required
before_install:
- sudo apt-get install asciidoctor
- sudo gem install pygments.rb
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- asciidoctor README.adoc -o docs/index.html
- asciidoctor README-TEST.adoc -o docs/otherdoc.html
after_success:
- sh push.sh
env:
  global:
    secure: W1go7MepUKv6uwFaVZRKff9a3wPeQkXeD2QgYNDxpRsF7PMfXpFaDO2UMmNiwwPqQiCgtc89HR7VlcFuGs9UJYHEN5x5x/tHdMIRNMfafoGX9wUe3+/Igl0MTvlhV2jGhJRBOi0j1wxCTqk7AYyxZQrDsJbOwTlyp7MEuKUP88ATTjqOOKLOAxnh7tTYvkt6tM9nbkkSFysX6AQYez4eoTkcjPF/HLJzCcu4hEKt8aQCf9CECfJ6e/Xhl4n60ppRFP9mFxCtoz4Bt6yYIcYio/G8EQjW7bV9bIYtQqaeYVC+eHpdSMnY0d9ApuKY9anNjX3Oft2MbpuuqiW/QWI9/ze3z583oShWZyGZ+SiopJu7f5jk6j1xojbdFnX5xjKCy9ZxJMq1/egV0r+GDApKBnk1ecnovaqlOmTLDf0SE8JVZhuVMgWJLO4SbYs1ZJnmAsporBo6SD+FU0ZovGIYeJMauwu90idv3Y3KkKHoZC1Y2O8lNP3TL5HaWkEQ6AGHO9mUQgJmwnOW9WNlOl8a6/sSjAkYCdJA8Gt6/btKuu6omquMzFns9o0cnF4kbE3hTAtlJKaoH/Es1qYrvLEWpbkWu8WTQBiSXcfnsT48fWocL5KbHu3ONK1zVyblhp6Nu2pH0sF7T8S57d0K+j39JEaXahPyDM9VQ3AukH1z+8c=
