sudo: required

services:
  - docker

before_install:
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/docs/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor README.adoc -o /docs/index.html

after_error:
  - docker logs asciidoc-to-html
